--
--	jtbl.vhd
--
--	jump table for java bc to jvm address
--
--		DONT edit this file!
--		generated by Jopa.java
--

library ieee;
use ieee.std_logic_1164.all;
use ieee.std_logic_arith.all;
use ieee.std_logic_unsigned.all;

entity jtbl is
port (
	bcode	: in std_logic_vector(7 downto 0);
	int_pend	: in  std_logic;
	exc_pend	: in  std_logic;
	q		: out std_logic_vector(10 downto 0)
);
end jtbl;

--
--	unregistered rdbcode
--	unregistered dout
--
architecture rtl of jtbl is

	signal	addr	: std_logic_vector(10 downto 0);

begin

process(bcode) begin

	case bcode is

		when "00000000" => addr <= "00010010111";	--	0097	nop
		when "00000010" => addr <= "00010011000";	--	0098	iconst_m1
		when "00000001" => addr <= "00010011001";	--	0099	aconst_null
		when "00000011" => addr <= "00010011001";	--	0099	iconst_0
		when "00000100" => addr <= "00010011010";	--	009a	iconst_1
		when "00000101" => addr <= "00010011011";	--	009b	iconst_2
		when "00000110" => addr <= "00010011100";	--	009c	iconst_3
		when "00000111" => addr <= "00010011101";	--	009d	iconst_4
		when "00001000" => addr <= "00010011110";	--	009e	iconst_5
		when "00010000" => addr <= "00010011111";	--	009f	bipush
		when "00010001" => addr <= "00010100001";	--	00a1	sipush
		when "00010010" => addr <= "00010100100";	--	00a4	ldc
		when "00010011" => addr <= "00010101011";	--	00ab	ldc_w
		when "00011001" => addr <= "00010110011";	--	00b3	aload
		when "00010111" => addr <= "00010110011";	--	00b3	fload
		when "00010101" => addr <= "00010110011";	--	00b3	iload
		when "00101010" => addr <= "00010110101";	--	00b5	aload_0
		when "00100010" => addr <= "00010110101";	--	00b5	fload_0
		when "00011010" => addr <= "00010110101";	--	00b5	iload_0
		when "00101011" => addr <= "00010110110";	--	00b6	aload_1
		when "00100011" => addr <= "00010110110";	--	00b6	fload_1
		when "00011011" => addr <= "00010110110";	--	00b6	iload_1
		when "00101100" => addr <= "00010110111";	--	00b7	aload_2
		when "00100100" => addr <= "00010110111";	--	00b7	fload_2
		when "00011100" => addr <= "00010110111";	--	00b7	iload_2
		when "00101101" => addr <= "00010111000";	--	00b8	aload_3
		when "00100101" => addr <= "00010111000";	--	00b8	fload_3
		when "00011101" => addr <= "00010111000";	--	00b8	iload_3
		when "00111010" => addr <= "00010111001";	--	00b9	astore
		when "00111000" => addr <= "00010111001";	--	00b9	fstore
		when "00110110" => addr <= "00010111001";	--	00b9	istore
		when "01001011" => addr <= "00010111011";	--	00bb	astore_0
		when "01000011" => addr <= "00010111011";	--	00bb	fstore_0
		when "00111011" => addr <= "00010111011";	--	00bb	istore_0
		when "01001100" => addr <= "00010111100";	--	00bc	astore_1
		when "01000100" => addr <= "00010111100";	--	00bc	fstore_1
		when "00111100" => addr <= "00010111100";	--	00bc	istore_1
		when "01001101" => addr <= "00010111101";	--	00bd	astore_2
		when "01000101" => addr <= "00010111101";	--	00bd	fstore_2
		when "00111101" => addr <= "00010111101";	--	00bd	istore_2
		when "01001110" => addr <= "00010111110";	--	00be	astore_3
		when "01000110" => addr <= "00010111110";	--	00be	fstore_3
		when "00111110" => addr <= "00010111110";	--	00be	istore_3
		when "01010111" => addr <= "00010111111";	--	00bf	pop
		when "01011000" => addr <= "00011000000";	--	00c0	pop2
		when "01011001" => addr <= "00011000010";	--	00c2	dup
		when "01011010" => addr <= "00011000011";	--	00c3	dup_x1
		when "01011011" => addr <= "00011001000";	--	00c8	dup_x2
		when "01011100" => addr <= "00011001111";	--	00cf	dup2
		when "01011101" => addr <= "00011010101";	--	00d5	dup2_x1
		when "01011110" => addr <= "00011011101";	--	00dd	dup2_x2
		when "01011111" => addr <= "00011100111";	--	00e7	swap
		when "01100000" => addr <= "00011101011";	--	00eb	iadd
		when "01100100" => addr <= "00011101100";	--	00ec	isub
		when "01110100" => addr <= "00011101101";	--	00ed	ineg
		when "01111110" => addr <= "00011110001";	--	00f1	iand
		when "10000000" => addr <= "00011110010";	--	00f2	ior
		when "10000010" => addr <= "00011110011";	--	00f3	ixor
		when "01111000" => addr <= "00011110100";	--	00f4	ishl
		when "01111010" => addr <= "00011110101";	--	00f5	ishr
		when "01111100" => addr <= "00011110110";	--	00f6	iushr
		when "01101000" => addr <= "00011110111";	--	00f7	imul
		when "10000100" => addr <= "00100000011";	--	0103	iinc
		when "10010010" => addr <= "00100001011";	--	010b	i2c
		when "11000110" => addr <= "00100001101";	--	010d	ifnull
		when "11000111" => addr <= "00100001101";	--	010d	ifnonnull
		when "10011001" => addr <= "00100001101";	--	010d	ifeq
		when "10011010" => addr <= "00100001101";	--	010d	ifne
		when "10011011" => addr <= "00100001101";	--	010d	iflt
		when "10011100" => addr <= "00100001101";	--	010d	ifge
		when "10011101" => addr <= "00100001101";	--	010d	ifgt
		when "10011110" => addr <= "00100001101";	--	010d	ifle
		when "10100101" => addr <= "00100010001";	--	0111	if_acmpeq
		when "10100110" => addr <= "00100010001";	--	0111	if_acmpne
		when "10011111" => addr <= "00100010001";	--	0111	if_icmpeq
		when "10100000" => addr <= "00100010001";	--	0111	if_icmpne
		when "10100001" => addr <= "00100010001";	--	0111	if_icmplt
		when "10100010" => addr <= "00100010001";	--	0111	if_icmpge
		when "10100011" => addr <= "00100010001";	--	0111	if_icmpgt
		when "10100100" => addr <= "00100010001";	--	0111	if_icmple
		when "10100111" => addr <= "00100010101";	--	0115	goto
		when "11100000" => addr <= "00100011001";	--	0119	getstatic_ref
		when "10110010" => addr <= "00100011001";	--	0119	getstatic
		when "10110011" => addr <= "00100100000";	--	0120	putstatic
		when "11100010" => addr <= "00100101000";	--	0128	getfield_ref
		when "10110100" => addr <= "00100101000";	--	0128	getfield
		when "11101001" => addr <= "00100101011";	--	012b	jopsys_getfield
		when "10110101" => addr <= "00100110000";	--	0130	putfield
		when "11101010" => addr <= "00100110100";	--	0134	jopsys_putfield
		when "10111100" => addr <= "00100111001";	--	0139	newarray
		when "10111110" => addr <= "00101010000";	--	0150	arraylength
		when "01010100" => addr <= "00101010110";	--	0156	bastore
		when "01010101" => addr <= "00101010110";	--	0156	castore
		when "01010001" => addr <= "00101010110";	--	0156	fastore
		when "01001111" => addr <= "00101010110";	--	0156	iastore
		when "01010110" => addr <= "00101010110";	--	0156	sastore
		when "00110010" => addr <= "00101011100";	--	015c	aaload
		when "00110011" => addr <= "00101011100";	--	015c	baload
		when "00110100" => addr <= "00101011100";	--	015c	caload
		when "00110000" => addr <= "00101011100";	--	015c	faload
		when "00101110" => addr <= "00101011100";	--	015c	iaload
		when "00110101" => addr <= "00101011100";	--	015c	saload
		when "11000010" => addr <= "00101100001";	--	0161	monitorenter
		when "11000011" => addr <= "00101110011";	--	0173	monitorexit
		when "10110111" => addr <= "00110000111";	--	0187	invokespecial
		when "10111000" => addr <= "00110000111";	--	0187	invokestatic
		when "11011110" => addr <= "00110001111";	--	018f	jopsys_invoke
		when "10111001" => addr <= "00110010011";	--	0193	invokeinterface
		when "11101100" => addr <= "00111000101";	--	01c5	invokesuper
		when "10110110" => addr <= "00111110100";	--	01f4	invokevirtual
		when "10110000" => addr <= "01001010110";	--	0256	areturn
		when "10101110" => addr <= "01001010110";	--	0256	freturn
		when "10101100" => addr <= "01001010110";	--	0256	ireturn
		when "10101111" => addr <= "01001101101";	--	026d	dreturn
		when "10101101" => addr <= "01001101101";	--	026d	lreturn
		when "10110001" => addr <= "01010000110";	--	0286	return
		when "00010100" => addr <= "01010101111";	--	02af	ldc2_w
		when "00001001" => addr <= "01011000000";	--	02c0	lconst_0
		when "00001010" => addr <= "01011000010";	--	02c2	lconst_1
		when "10001000" => addr <= "01011000100";	--	02c4	l2i
		when "00100110" => addr <= "01011000111";	--	02c7	dload_0
		when "00011110" => addr <= "01011000111";	--	02c7	lload_0
		when "00100111" => addr <= "01011001001";	--	02c9	dload_1
		when "00011111" => addr <= "01011001001";	--	02c9	lload_1
		when "00101000" => addr <= "01011001011";	--	02cb	dload_2
		when "00100000" => addr <= "01011001011";	--	02cb	lload_2
		when "00101001" => addr <= "01011001101";	--	02cd	dload_3
		when "00100001" => addr <= "01011001101";	--	02cd	lload_3
		when "00011000" => addr <= "01011011000";	--	02d8	dload
		when "00010110" => addr <= "01011011000";	--	02d8	lload
		when "01000111" => addr <= "01011100011";	--	02e3	dstore_0
		when "00111111" => addr <= "01011100011";	--	02e3	lstore_0
		when "01001000" => addr <= "01011100101";	--	02e5	dstore_1
		when "01000000" => addr <= "01011100101";	--	02e5	lstore_1
		when "01001001" => addr <= "01011100111";	--	02e7	dstore_2
		when "01000001" => addr <= "01011100111";	--	02e7	lstore_2
		when "01001010" => addr <= "01011101001";	--	02e9	dstore_3
		when "01000010" => addr <= "01011101001";	--	02e9	lstore_3
		when "00111001" => addr <= "01011110100";	--	02f4	dstore
		when "00110111" => addr <= "01011110100";	--	02f4	lstore
		when "11100100" => addr <= "01011111111";	--	02ff	getstatic_long
		when "11100101" => addr <= "01100001111";	--	030f	putstatic_long
		when "11100110" => addr <= "01100100000";	--	0320	getfield_long
		when "11100111" => addr <= "01100111010";	--	033a	putfield_long
		when "01010000" => addr <= "01101010111";	--	0357	lastore
		when "00101111" => addr <= "01110000111";	--	0387	laload
		when "10111011" => addr <= "01111011011";	--	03db	new
		when "10111101" => addr <= "01111011011";	--	03db	anewarray
		when "11000000" => addr <= "01111011011";	--	03db	checkcast
		when "11000001" => addr <= "01111011011";	--	03db	instanceof
		when "11100011" => addr <= "01111111000";	--	03f8	putfield_ref
		when "11100001" => addr <= "01111111000";	--	03f8	putstatic_ref
		when "11010001" => addr <= "10000010000";	--	0410	jopsys_rd
		when "11010011" => addr <= "10000010000";	--	0410	jopsys_rdmem
		when "11010010" => addr <= "10000010100";	--	0414	jopsys_wr
		when "11010100" => addr <= "10000010100";	--	0414	jopsys_wrmem
		when "11010101" => addr <= "10000011001";	--	0419	jopsys_rdint
		when "11010110" => addr <= "10000011100";	--	041c	jopsys_wrint
		when "11010111" => addr <= "10000011111";	--	041f	jopsys_getsp
		when "11011000" => addr <= "10000100010";	--	0422	jopsys_setsp
		when "11011001" => addr <= "10000100110";	--	0426	jopsys_getvp
		when "11011010" => addr <= "10000100111";	--	0427	jopsys_setvp
		when "11011011" => addr <= "10000101001";	--	0429	jopsys_int2ext
		when "11011100" => addr <= "10001000100";	--	0444	jopsys_ext2int
		when "11101000" => addr <= "10001100000";	--	0460	jopsys_memcpy
		when "11011101" => addr <= "10001100101";	--	0465	jopsys_nop

		when others => addr <= "01111001000";		--	03c8	sys_noim
	end case;
end process;

process(int_pend, exc_pend, addr) begin

	q <= addr;
	if exc_pend='1' then
		q <= "01110111100";		--	03bc	sys_exc
	elsif int_pend='1' then
		q <= "01110110010";		--	03b2	sys_int
	end if;
end process;

end rtl;
